name: "tell it stackfield"
description: "webhook"
inputs:
  message:
    description: "message"
    required: false
  webhook:
    description: "Send webhook event notifications"
    required: false

runs:
  using: "composite"
  steps:
    - name: "call webhook"
      shell: bash
      run: |
        echo "::group::Initialization"
        function send_webhook() {

          local post_data="•  _GITHUB ACTION MESSAGE_\n*${{inputs.message}}*\n${{ github.repository }}\n${{ github.event.head_commit.url }}\n${{ github.event.head_commit.author.name }} \n+${{ github.event.head_commit.message }}+"

          

          curl --data "{\"Title\":\"${post_data}\"}" --header "Content-Type: application/json" --max-time 30 --show-error --silent --user-agent "GitHub Workflow" "${{inputs.webhook}}"
        }
        echo "::endgroup::"



        echo "::group::POST"
        [ "${{inputs.webhook}}" != "" ] && echo "Webhook notification (send message): $(send_webhook)"
        echo "::endgroup::"



        exit 0
