name: 'tell it mattermost'
description: 'webhook'
inputs:
  destination:
    description: 'examples: :clapper: *Live* / :closed_lock_with_key: *Staging*'
    required: false
    default: ':clapper: *Live*'
  message:
    description: 'message'
    required: false
    # :white_check_mark: :warning: :test_tube: ...
  webhook:
    description: 'Send webhook event notifications'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'call webhook'
      shell: bash
      run: |
        echo "::group::Initialization"
        function send_webhook() {
          local message="$1"
          local destination="$2"
          local post_data="|  |  |  |\n| :------------ |:---------------:| :----- |\n| [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) | ${{ github.event.head_commit.message }} | :bust_in_silhouette: ${{ github.actor }} |\n| $(date '+%H:%M:%S') | ${{inputs.message}} | ${{inputs.destination}} |"

          curl --data "{\"text\":\"${post_data}\"}" --header "Content-Type: application/json" --max-time 30 --show-error --silent --user-agent "GitHub Workflow" "${{inputs.webhook}}"
        }
        echo "::endgroup::"



        echo "::group::POST"
        [ "${{inputs.webhook}}" != "" ] && echo "Webhook notification (send message): $(send_webhook "${{inputs.message}}" "${{inputs.destination}}")"
        echo "::endgroup::"



        exit 0
