name: 'tell it mattermost'
description: 'webhook'
inputs:
  message:
    description: 'message'
    required: false
    # :white_check_mark: :warning: :test_tube: ...
  webhook:
    description: 'Send webhook event notifications'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'call webhook'
      shell: bash
      run: |
        echo "::group::Initialization"
        function send_webhook() {
          local status="$1"
          local post_data="[${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) ${status}\n##### $(date '+%Y-%m-%d %H:%M:%S') - ${{ github.event.head_commit.message }} \nactor: ${{ github.actor }}"

          curl --data "{\"text\":\"${post_data}\"}" --header "Content-Type: application/json" --max-time 30 --show-error --silent --user-agent "GitHub Workflow" "${{inputs.webhook}}"
        }
        echo "::endgroup::"



        echo "::group::POST"
        [ "${{inputs.webhook}}" != "" ] && echo "Webhook notification (send message): $(send_webhook "${{inputs.message}}")"
        echo "::endgroup::"



        exit 0
