name: release-github-actions
on:
  push:
    branches:
      - 'main'

# Save remote version
# BUILD
# Test
# Delete old version / Reset to old version

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook (Stackfield)
        uses: Tueftlerei/github_actions/.github/actions/stackfield@main
        with:
          #
          message: 'TEST STACKFIELD_WEBHOOK'
          #
          webhook: ${{ secrets.STACKFIELD_WEBHOOK }}
